name: user_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  cloud_firestore: ^5.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  test: ^1.21.0
